language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - env: ILLUMINATE_VERSION=5.8.* TESTBENCH_VERSION=3.8.*
      php: 7.2
    - env: ILLUMINATE_VERSION=5.8.* TESTBENCH_VERSION=3.8.*
      php: 7.3

before_install:
  - composer require "illuminate/support:${ILLUMINATE_VERSION}" --no-update -v
  - composer require "illuminate/console:${ILLUMINATE_VERSION}" --no-update -v
  - composer require "illuminate/filesystem:${ILLUMINATE_VERSION}" --no-update -v
  - composer require "orchestra/testbench:${TESTBENCH_VERSION}" --dev --no-update -v

install:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-dist --no-suggest

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover